# To be used if weld already exists on your device

[project]
name = "weld"
type = "ConsoleApp"

[files]
cextensions = [".cpp"]

[settings]
toolset = "g++"
src_dir = "src"
out_dir = "bin"

[gnuc]
cflags = ["-O3"]

[install]
install_path = "/usr/bin"