[project]
name = "member2"
type = "ConsoleApp"

[files]
extensions = [".cpp"]

[settings]
toolset = "g++"
src_dir = "src"
out_dir = "out"

[gnuc]
#cflags = ["-O2"]
#lflags = [""]

[dependencies]
member1 = { path = "../member1", include = true }